import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const workflowPath = new URL('../.github/workflows/akinael-agent.yml', import.meta.url);

test('central Akinael runner keeps the customer-repository security contract', async () => {
  const workflow = await readFile(workflowPath, 'utf8');
  assert.match(workflow, /workflow_dispatch:/);
  assert.match(workflow, /target_repository:/);
  assert.match(workflow, /actions\/create-github-app-token@v2/);
  assert.match(workflow, /repository:\s*\$\{\{ inputs\.target_repository \}\}/);
  assert.match(workflow, /persist-credentials:\s*false/);
  assert.match(workflow, /openai\/codex-action@52fe01ec70a42f454c9d2ebd47598f9fd6893d56/);
  assert.match(workflow, /codex-version:\s*['"]0\.150\.0['"]/);
  assert.match(workflow, /default:\s*gpt-5\.6-terra/);
  assert.match(workflow, /model:\s*\$\{\{ inputs\.model \}\}/);
  assert.match(workflow, /effort:\s*\$\{\{ inputs\.effort \}\}/);
  assert.doesNotMatch(workflow, /openai\/codex-action@v1(?:\s|$)/);
  assert.match(workflow, /timeout-minutes:\s*90/);
  assert.match(workflow, /permission-profile:\s*\$\{\{ inputs\.permission_profile \}\}/);
  assert.match(workflow, /task_mode:/);
  assert.match(workflow, /inputs\.task_mode == 'visual_review' && inputs\.stage == 'review'/);
  assert.match(workflow, /viewport-360\.png/);
  assert.match(workflow, /viewport-768\.png/);
  assert.match(workflow, /viewport-1280\.png/);
  assert.match(workflow, /codex-args:.*--image/);
  assert.match(workflow, /safety-strategy:\s*drop-sudo/);
  assert.match(workflow, /AKINAEL_GITHUB_APP_ID:\s*['"]4762113['"]/);
  assert.match(workflow, /app-id:\s*\$\{\{ env\.AKINAEL_GITHUB_APP_ID \}\}/);
  assert.match(workflow, /AKINAEL_BOT_USER:\s*['"]akinael-ai-runtime-yufi\[bot\]['"]/);
  assert.match(workflow, /allow-bot-users:\s*\$\{\{ env\.AKINAEL_BOT_USER \}\}/);
  assert.doesNotMatch(workflow, /allow-bots:\s*true/);
  assert.match(workflow, /npm run qa/);
  assert.match(workflow, /playwright install --with-deps\n/);
  assert.doesNotMatch(workflow, /playwright install --with-deps chromium/);
  assert.match(workflow, /code=1/);
  assert.match(workflow, /Protected path changed/);
  assert.match(workflow, /\.akinael\/results/);
  assert.doesNotMatch(workflow, /rm -rf \\.codex \\.akinael/);
  assert.match(workflow, /git rebase FETCH_HEAD/);
  assert.match(workflow, /permissions:\n\s+contents:\s+read/);
  assert.doesNotMatch(workflow, /pull_request_target/);
});
