import { FormEvent, ReactNode, useCallback, useEffect, useMemo, useState } from "react";

type Row = Record<string, unknown> & { id:string; title?:string; status?:string; created_at?:string; updated_at?:string; preview_url?:string|null };
type Project = Row & { name:string; customer_id?:string; customer_name?:string|null; needs_attention?:boolean; attention_reasons?:string[] };
type Summary = { customers:number; projects:number; needsAttention:number; runningWorkflows:number; failedTasks:number; pendingApprovals:number };
type Overview = { summary:Summary; projects:Project[]; recentWorkflows:Row[]; recentNotifications:Row[] };
type Detail = { project:Project; customer?:Row|null; requests:Row[]; messages:Row[]; workflows:Row[]; tasks:Row[]; artifacts:Row[]; qualityChecks:Row[]; approvals:Row[]; payments:Row[]; repositories:Row[]; deployments:Row[]; notifications:Row[]; deploymentGate:{ releasePassed:boolean; customerApproved:boolean; deployReady:boolean; humanGateRequired:boolean; productionPublished:boolean }; auditLogs:Row[] };
type Me = { profile?:{role?:string; displayName?:string}; user?:{email?:string} };
type Screen = "home"|"customers"|"customer"|"projects"|"project"|"chat"|"consultation"|"deliverables"|"billing"|"settings"|"guide"|"developer";
type StatusKey = "new"|"needs_admin"|"in_progress"|"needs_customer"|"done"|"error";

const core = import.meta.env.VITE_CORE_API_URL || "https://akinael-ai.com";
const tokenKey = "akinael-admin-token";
const string = (v:unknown) => typeof v === "string" ? v : "";
const fmt = (v:unknown, time=false) => string(v) ? new Intl.DateTimeFormat("ja-JP", time ? {dateStyle:"medium",timeStyle:"short"}:{dateStyle:"medium"}).format(new Date(string(v))) : "—";
const money = (v:unknown) => typeof v === "number" ? new Intl.NumberFormat("ja-JP",{style:"currency",currency:"JPY",maximumFractionDigits:0}).format(v) : "—";
const statusOf = (p:Project, d?:Detail):StatusKey => {
  const raw=string(p.status).toLowerCase();
  if (d?.tasks.some(x=>x.status==="failed")) return "error";
  if (d?.deploymentGate.productionPublished || ["completed","done","published"].includes(raw)) return "done";
  if (p.needs_attention || d?.approvals.some(x=>x.status==="pending")) return "needs_admin";
  if (d?.deploymentGate.customerApproved===false && d?.artifacts.length) return "needs_customer";
  if (d?.workflows.some(x=>["running","queued"].includes(string(x.status)))) return "in_progress";
  if (["intake","new","draft"].includes(raw)) return "new";
  return d?.workflows.length ? "in_progress" : "new";
};
const statusMeta:Record<StatusKey,{label:string; next:string}> = {
  new:{label:"新規相談",next:"相談内容を確認してください"}, needs_admin:{label:"あなたの判断待ち",next:"内容を確認し、次の対応を判断してください"}, in_progress:{label:"制作中",next:"AIチームが作業を進めています"}, needs_customer:{label:"お客様確認待ち",next:"お客様からの確認を待っています"}, done:{label:"完了",next:"対応は完了しています"}, error:{label:"要対応",next:"処理エラーの確認が必要です"}
};

function Icon({name,size=18}:{name:string;size?:number}) {
  const paths:Record<string,ReactNode>={home:<><path d="M3 11l9-7 9 7"/><path d="M5 10v10h5v-6h4v6h5V10"/></>,users:<><circle cx="9" cy="8" r="3"/><path d="M3 20c.5-4 3-6 6-6s5.5 2 6 6M17 4a3 3 0 0 1 0 6M17 14c2.3.4 3.7 2.4 4 6"/></>,folder:<path d="M3 7h6l2 2h10v11H3z"/>,chat:<path d="M4 5h16v11H10l-5 4v-4H4z"/>,image:<><rect x="3" y="4" width="18" height="16"/><circle cx="8" cy="9" r="1.5"/><path d="M4 18l5-5 3 3 4-5 5 6"/></>,card:<><rect x="2" y="5" width="20" height="14"/><path d="M2 10h20"/></>,settings:<><circle cx="12" cy="12" r="3"/><path d="M19 13a7 7 0 0 0 0-2l2-2-2-3-3 1a8 8 0 0 0-2-1l-1-3h-3L9 6a8 8 0 0 0-2 1L4 6 2 9l2 2a7 7 0 0 0 0 2l-2 2 2 3 3-1a8 8 0 0 0 2 1l1 3h3l1-3a8 8 0 0 0 2-1l3 1 2-3z"/></>,refresh:<><path d="M20 6v5h-5"/><path d="M19 11a8 8 0 1 0 1 5"/></>,logout:<><path d="M10 4H4v16h6M14 8l4 4-4 4M9 12h9"/></>,chevron:<path d="M9 6l6 6-6 6"/>,back:<><path d="M19 12H5M11 6l-6 6 6 6"/></>,sparkle:<><path d="M12 3l1.5 4L18 9l-4.5 1.5L12 15l-1.5-4.5L6 9l4.5-2z"/><path d="M19 15l.7 2 2 .7-2 .7-.7 2-.7-2-2-.7 2-.7z"/></>,alert:<><circle cx="12" cy="12" r="9"/><path d="M12 7v6M12 17h.01"/></>,check:<path d="M5 12l4 4L19 6"/>,send:<path d="M3 11l18-8-8 18-2-8z"/>,external:<><path d="M14 4h6v6M20 4l-9 9"/><path d="M18 13v7H4V6h7"/></>};
  return <svg aria-hidden="true" viewBox="0 0 24 24" width={size} height={size} fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}
function Corners(){return <><i className="corner tl"/><i className="corner tr"/><i className="corner bl"/><i className="corner br"/></>}
function Tag({status,children}:{status?:StatusKey|string;children:ReactNode}){return <span className={`tag tag-${status||"neutral"}`}>{children}</span>}
function Empty({children}:{children:ReactNode}){return <div className="empty">{children}</div>}

export default function Admin(){
  const hash=new URLSearchParams(window.location.hash.replace(/^#/,"")); const recoveryToken=hash.get("access_token");
  const [token,setToken]=useState<string|null>(null),[me,setMe]=useState<Me|null>(null),[overview,setOverview]=useState<Overview|null>(null),[details,setDetails]=useState<Record<string,Detail>>({}),[selected,setSelected]=useState(""),[screen,setScreen]=useState<Screen>("home");
  const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState(""),[recoveryMode,setRecoveryMode]=useState(new URLSearchParams(window.location.search).get("mode")==="recovery"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[search,setSearch]=useState(""),[filter,setFilter]=useState<"all"|StatusKey>("all");
  const authHeaders=useCallback((v=token):Record<string,string>=>v?{authorization:`Bearer ${v}`}:{},[token]);
  const api=useCallback(async<T,>(path:string,v=token):Promise<T>=>{const r=await fetch(`${core}${path}`,{headers:authHeaders(v)});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b?.error?.message||"管理データを取得できませんでした");return b as T},[authHeaders,token]);
  const load=useCallback(async(v=token)=>{if(!v)return;setBusy(true);try{const [who,board]=await Promise.all([api<Me>("/api/v2/auth/me",v),api<Overview>("/api/v2/admin/overview",v)]);if(who.profile?.role!=="admin")throw Error("管理者権限がありません。");const entries=await Promise.all(board.projects.map(async p=>[p.id,await api<Detail>(`/api/v2/admin/projects/${p.id}`,v)] as const));setMe(who);setOverview(board);setDetails(Object.fromEntries(entries));setSelected(s=>s||board.projects[0]?.id||"")}finally{setBusy(false)}},[api,token]);
  useEffect(()=>{const saved=localStorage.getItem(tokenKey);if(saved){setToken(saved);load(saved).catch(e=>{localStorage.removeItem(tokenKey);setToken(null);setError(e.message)})}},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const login=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch(`${core}/api/v2/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})});const b=await r.json();if(!r.ok)throw Error(b?.error?.message||"ログインに失敗しました");localStorage.setItem(tokenKey,b.token);setToken(b.token);await load(b.token)}catch(e){setError(e instanceof Error?e.message:"ログインに失敗しました")}finally{setBusy(false)}};
  const requestRecovery=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch(`${core}/api/v2/auth/password-recovery`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b?.error?.message||"再設定メールを送信できませんでした");setNotice("パスワード再設定メールを送信しました。メール内のリンクを開いてください。")}catch(e){setError(e instanceof Error?e.message:"再設定メールを送信できませんでした")}finally{setBusy(false)}};
  const logout=useCallback(async()=>{if(token)await fetch(`${core}/api/v2/auth/logout`,{method:"POST",headers:authHeaders()}).catch(()=>{});localStorage.removeItem(tokenKey);setToken(null);setMe(null);setOverview(null);setDetails({})},[authHeaders,token]);
  const updatePassword=async(e:FormEvent)=>{e.preventDefault();if(password!==confirmPassword){setError("確認用パスワードが一致しません。");return}if(!recoveryToken){setError("回復リンクが無効です。再設定メールをもう一度送信してください。");return}setBusy(true);try{const r=await fetch(`${core}/api/v2/auth/password`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${recoveryToken}`},body:JSON.stringify({password})});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b?.error?.message||"パスワードを更新できませんでした");await logout();window.history.replaceState({},"","/admin/");setRecoveryMode(false);setNotice("パスワードを更新しました。新しいパスワードでログインしてください。")}catch(e){setError(e instanceof Error?e.message:"パスワードを更新できませんでした")}finally{setBusy(false)}};
  const go=(next:Screen,id?:string)=>{if(id)setSelected(id);else if(next==="chat")setSelected("");setScreen(next);window.scrollTo(0,0)}; const projects=overview?.projects||[]; const detail=details[selected];
  const customers=useMemo(()=>{const map=new Map<string,{id:string;name:string;projects:Project[];updated?:string}>();projects.forEach(p=>{const id=p.customer_id||p.customer_name||p.id;const current=map.get(id)||{id,name:p.customer_name||string(details[p.id]?.customer?.name)||"顧客未設定",projects:[],updated:p.updated_at};current.projects.push(p);if(string(p.updated_at)>string(current.updated))current.updated=p.updated_at;map.set(id,current)});return [...map.values()]},[projects,details]);
  const nav=[['home','home','ホーム'],['customers','users','顧客'],['projects','folder','案件'],['chat','chat','AIチャット'],['deliverables','image','制作物'],['billing','card','契約・料金'],['settings','settings','設定']] as [Screen,string,string][];
  const active=(id:Screen)=> id==="customers"?screen==="customers"||screen==="customer":id==="projects"?screen==="projects"||screen==="project"||screen==="consultation":id==="settings"?["settings","guide","developer"].includes(screen):screen===id;
  if(recoveryMode||!token||!me)return <main className="login-shell"><section className="login-card blueprint"><Corners/><div className="brand">AKINAEL<span>AI</span></div><p className="kicker">OPERATIONS CONSOLE</p><h1>{recoveryMode?(recoveryToken?"新しいパスワード":"パスワード再設定"):"管理者ログイン"}</h1><p className="muted">{recoveryMode?(recoveryToken?"12文字以上の新しいパスワードを設定します。":"登録済みメールアドレスへ回復リンクを送信します。"):"運営者アカウントでログインしてください。"}</p>{error&&<p className="alert" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}{recoveryMode?(recoveryToken?<form onSubmit={updatePassword}><label>新しいパスワード<input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} required/></label><label>新しいパスワード（確認）<input className="input" type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} minLength={12} required/></label><button className="btn btn-primary" disabled={busy}>パスワードを更新</button></form>:<form onSubmit={requestRecovery}><label>メールアドレス<input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><button className="btn btn-primary" disabled={busy}>再設定メールを送信</button></form>):<form onSubmit={login}><label>メールアドレス<input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>パスワード<input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} required/></label><button className="btn btn-primary" disabled={busy}>{busy?"認証中…":"管理画面へ"}</button></form>}<div className="login-links"><button onClick={()=>{setRecoveryMode(!recoveryMode);setError("")}}>{recoveryMode?"ログインへ戻る":"パスワードを忘れた方"}</button><a href="/portal/">顧客マイページへ</a></div></section></main>;
  return <div className="app-shell"><aside className="sidebar"><div className="brand">AKINAEL<span>AI</span></div><nav>{nav.map(([id,icon,label])=><button key={id} className={active(id)?"active":""} onClick={()=>go(id)}><Icon name={icon}/>{label}</button>)}</nav><div className="account"><strong>{me.profile?.displayName||"管理者"}</strong><small>{me.user?.email}</small><div><button aria-label="データを更新" onClick={()=>load()} disabled={busy}><Icon name="refresh" size={16}/></button><button aria-label="ログアウト" onClick={logout}><Icon name="logout" size={16}/></button></div></div></aside><main className="main">{error&&<p className="alert" role="alert">{error}</p>}{busy&&!overview?<div className="loading">管理データを読み込んでいます…</div>:<ScreenView screen={screen} go={go} overview={overview!} projects={projects} details={details} detail={detail} customers={customers} search={search} setSearch={setSearch} filter={filter} setFilter={setFilter}/>}</main><nav className="bottom-nav">{nav.filter(([id])=>["home","projects","chat","deliverables","settings"].includes(id)).map(([id,icon,label])=><button key={id} className={active(id)?"active":""} onClick={()=>go(id)}><Icon name={icon}/><span>{label.replace("AI","")}</span></button>)}</nav></div>;
}

type ViewProps={screen:Screen;go:(s:Screen,id?:string)=>void;overview:Overview;projects:Project[];details:Record<string,Detail>;detail?:Detail;customers:{id:string;name:string;projects:Project[];updated?:string}[];search:string;setSearch:(v:string)=>void;filter:"all"|StatusKey;setFilter:(v:"all"|StatusKey)=>void};
function ScreenView(p:ViewProps){const {screen,go,overview,projects,details,detail,customers}=p;
  if(screen==="home"){const actions=projects.filter(x=>["needs_admin","error"].includes(statusOf(x,details[x.id])));const counts=(s:StatusKey)=>projects.filter(x=>statusOf(x,details[x.id])===s).length;return <Page title="ホーム" subtitle="今日、確認していただきたいことをまとめています。" narrow><section className="attention blueprint"><Corners/><div className="attention-count"><span>対応が必要</span><strong>{actions.length}件</strong></div>{actions.length?<div className="action-list">{actions.map(x=><button key={x.id} onClick={()=>go("project",x.id)}><i><Icon name={statusOf(x,details[x.id])==="error"?"alert":"sparkle"}/></i><span><strong>{x.name}</strong><small>{statusMeta[statusOf(x,details[x.id])].next}</small></span><em>内容を確認 <Icon name="chevron" size={14}/></em></button>)}</div>:<Empty>現在、対応が必要な案件はありません。</Empty>}</section><section className="stats">{([['in_progress','制作中'],['needs_customer','お客様確認待ち'],['done','完了'],['new','新規相談']] as [StatusKey,string][]).map(([key,label])=><button className="card blueprint" key={key} onClick={()=>{p.setFilter(key);go("projects")}}><Corners/><span>{label}</span><strong className={`text-${key}`}>{counts(key)}件</strong></button>)}</section></Page>}
  if(screen==="customers"){const rows=customers.filter(c=>c.name.toLowerCase().includes(p.search.toLowerCase()));return <Page title="顧客" header={<input aria-label="顧客を検索" className="input search" placeholder="顧客名・店舗名で検索" value={p.search} onChange={e=>p.setSearch(e.target.value)}/>}><div className="desktop-table"><table className="table"><thead><tr><th>顧客名 / 店舗名</th><th>案件数</th><th>最終更新</th><th>状態</th></tr></thead><tbody>{rows.map(c=><tr key={c.id} onClick={()=>go("customer",c.projects[0].id)}><td><strong>{c.name}</strong></td><td>{c.projects.length}件</td><td>{fmt(c.updated)}</td><td><Tag status={c.projects.some(x=>statusOf(x,details[x.id])!=="done")?"in_progress":"done"}>{c.projects.some(x=>statusOf(x,details[x.id])!=="done")?"対応中":"完了"}</Tag></td></tr>)}</tbody></table></div><div className="mobile-cards">{rows.map(c=><button className="card" key={c.id} onClick={()=>go("customer",c.projects[0].id)}><span><strong>{c.name}</strong><Tag status="in_progress">{c.projects.length}案件</Tag></span><small>最終更新 {fmt(c.updated)}</small></button>)}</div></Page>}
  if(screen==="customer"&&detail){const customer=customers.find(c=>c.id===detail.project.customer_id)||customers.find(c=>c.projects.some(x=>x.id===detail.project.id));return <Page title={customer?.name||"顧客詳細"} subtitle="顧客情報と進行中の案件" back={()=>go("customers")} narrow><div className="two-col"><section className="card"><p className="kicker">基本情報</p><dl><dt>顧客名</dt><dd>{customer?.name||"—"}</dd><dt>登録日</dt><dd>{fmt(detail.customer?.created_at)}</dd></dl></section><section className="card"><p className="kicker">ご利用状況</p><dl><dt>案件数</dt><dd>{customer?.projects.length||0}件</dd><dt>最終更新</dt><dd>{fmt(customer?.updated)}</dd></dl></section></div><h3 className="section-title">案件</h3><div className="stack">{customer?.projects.map(x=><button className="card row-card" key={x.id} onClick={()=>go("project",x.id)}><strong>{x.name}</strong><Tag status={statusOf(x,details[x.id])}>{statusMeta[statusOf(x,details[x.id])].label}</Tag></button>)}</div><button className="btn btn-secondary" onClick={()=>go("consultation",detail.project.id)}>過去の相談を見る</button></Page>}
  if(screen==="projects"){const filters:["all"|StatusKey,string][]=[["all","すべて"],["needs_admin","判断待ち"],["in_progress","制作中"],["needs_customer","お客様確認待ち"],["done","完了"],["new","新規相談"]];const rows=p.filter==="all"?projects:projects.filter(x=>statusOf(x,details[x.id])===p.filter);return <Page title="案件"><div className="chips">{filters.map(([key,label])=><button className={p.filter===key?"active":""} key={key} onClick={()=>p.setFilter(key)}>{label}</button>)}</div><div className="desktop-table"><table className="table"><thead><tr><th>案件名</th><th>顧客</th><th>状態</th><th>今やること</th><th>最終更新</th></tr></thead><tbody>{rows.map(x=>{const s=statusOf(x,details[x.id]);return <tr key={x.id} onClick={()=>go("project",x.id)}><td><strong>{x.name}</strong></td><td>{x.customer_name||"—"}</td><td><Tag status={s}>{statusMeta[s].label}</Tag></td><td>{statusMeta[s].next}</td><td>{fmt(x.updated_at)}</td></tr>})}</tbody></table></div><div className="mobile-cards">{rows.map(x=>{const s=statusOf(x,details[x.id]);return <button className="card" key={x.id} onClick={()=>go("project",x.id)}><span><strong>{x.name}</strong><Tag status={s}>{statusMeta[s].label}</Tag></span><small>{x.customer_name} · {fmt(x.updated_at)}</small><p>{statusMeta[s].next}</p></button>})}</div></Page>}
  if(screen==="project"&&detail)return <ProjectDetail detail={detail} go={go}/>;
  if(screen==="consultation"&&detail)return <Page title="お客様との相談" back={()=>go("project",detail.project.id)} header={<button className="btn btn-secondary" onClick={()=>go("chat",detail.project.id)}>この相談についてAIに聞く</button>} narrow>{detail.messages.length?<div className="timeline">{detail.messages.map(m=><article key={m.id} className={string(m.author_type)==="customer"?"customer":"ai"}><div><Tag status={string(m.author_type)==="customer"?"in_progress":"neutral"}>{string(m.author_type)==="customer"?"お客様":"相談役AI"}</Tag><time>{fmt(m.created_at,true)}</time></div><p>{string(m.content)||"内容なし"}</p></article>)}</div>:<Empty>この案件の相談履歴はまだありません。</Empty>}</Page>;
  if(screen==="chat")return <Chat projects={projects} details={details} detail={detail} go={go}/>;
  if(screen==="deliverables")return <Page title="制作物"><div className="deliverable-grid">{projects.flatMap(x=>details[x.id]?.artifacts.map(a=>({p:x,a}))||[]).map(({p:x,a})=><article className="card blueprint deliverable" key={a.id}><Corners/><div><strong>{x.name}</strong><Tag status={a.preview_url?"done":"in_progress"}>{a.preview_url?"確認できます":"制作済み"}</Tag></div><Tag status="neutral">AIが制作</Tag><div className="wireframe"><div><i/><span>PC</span></div><div><i/><span>スマホ</span></div></div>{a.preview_url?<a className="btn btn-secondary" href={a.preview_url} target="_blank" rel="noreferrer">プレビューを開く <Icon name="external" size={14}/></a>:<span className="muted small">プレビューは準備中です</span>}</article>)}</div>{!projects.some(x=>details[x.id]?.artifacts.length)&&<Empty>制作物はまだありません。</Empty>}</Page>;
  if(screen==="billing"){const rows=projects.flatMap(x=>(details[x.id]?.payments||[]).map(pay=>({project:x,pay})));return <Page title="契約・料金">{rows.length?<><div className="desktop-table"><table className="table"><thead><tr><th>顧客</th><th>案件</th><th>金額</th><th>状態</th><th>更新日</th></tr></thead><tbody>{rows.map(({project:x,pay})=><tr key={pay.id}><td>{x.customer_name||"—"}</td><td>{x.name}</td><td>{money(pay.amount)}</td><td><Tag status={pay.status==="failed"?"error":"done"}>{pay.status==="failed"?"支払いエラー":"処理済み"}</Tag></td><td>{fmt(pay.updated_at||pay.created_at)}</td></tr>)}</tbody></table></div><div className="mobile-cards">{rows.map(({project:x,pay})=><article className="card" key={pay.id}><span><strong>{x.customer_name}</strong><Tag status={pay.status==="failed"?"error":"done"}>{pay.status==="failed"?"支払いエラー":"処理済み"}</Tag></span><p>{x.name}</p><small>{money(pay.amount)} · {fmt(pay.updated_at||pay.created_at)}</small></article>)}</div></>:<Empty>契約・決済の記録はまだありません。</Empty>}<p className="muted small footer-note">決済や料金変更は、必ずオーナー確認後に実行します。</p></Page>}
  if(screen==="settings")return <Page title="設定" narrow><div className="settings-list"><span>基本情報<Icon name="chevron" size={16}/></span><span>通知設定<Icon name="chevron" size={16}/></span><span>担当者・権限<Icon name="chevron" size={16}/></span><button onClick={()=>go("guide")}>デザイン・運用ルール<Icon name="chevron" size={16}/></button></div><button className="developer-link" onClick={()=>go("developer")}>開発者向け情報</button></Page>;
  if(screen==="guide")return <Page title="デザイン・運用ルール" back={()=>go("settings")} narrow><Guide/></Page>;
  if(screen==="developer")return <Page title="開発者向け情報" back={()=>go("settings")} narrow><div className="card warning">この画面は通常運用では使用しません。技術的な内部状態の確認が必要な場合のみご利用ください。</div><div className="system-list"><span>自動処理の実行状況<b className="green">{overview.summary.runningWorkflows?"稼働中":"待機中"}</b></span><span>保留中の内部タスク<b>{overview.summary.pendingApprovals}件</b></span><span>直近のシステムエラー<b className={overview.summary.failedTasks?"red":"green"}>{overview.summary.failedTasks?`${overview.summary.failedTasks}件`:"なし"}</b></span><span>取得済み案件<b>{overview.summary.projects}件</b></span><span>最終同期<b>{fmt(new Date().toISOString(),true)}</b></span></div></Page>;
  return <Empty>表示できるデータがありません。</Empty>;
}

function ProjectDetail({detail,go}:{detail:Detail;go:(s:Screen,id?:string)=>void}){const p=detail.project,s=statusOf(p,detail),latest=detail.requests[0],payment=detail.payments[0],completed=detail.tasks.filter(x=>x.status==="completed").length;const summary=s==="done"?"制作と確認が完了しています。必要に応じて公開状況や次回のご提案をご確認ください。":s==="needs_admin"?"管理者による確認または判断を待っています。内容を確認して次の対応を決めてください。":s==="needs_customer"?"制作物をお客様に確認いただいています。返信が届くまでお待ちください。":s==="in_progress"?`AIチームが作業を進めています。現在 ${completed}/${detail.tasks.length} 件の作業が完了しています。`:"お客様との相談内容を整理しています。内容が確定すると制作へ進みます。";return <Page title={p.name} subtitle={p.customer_name||string(detail.customer?.name)||"顧客未設定"} back={()=>go("projects")} header={<Tag status={s}>{statusMeta[s].label}</Tag>} narrow><p className="project-meta">最終更新 {fmt(p.updated_at,true)} {payment&&<>・契約金額 {money(payment.amount)}</>}</p><div className="quick-links"><button className="btn btn-secondary" onClick={()=>go("consultation",p.id)}>お客様との相談</button><button className="btn btn-secondary" onClick={()=>go("chat",p.id)}>司令塔AIに相談</button><button className="btn btn-secondary" onClick={()=>go("deliverables",p.id)}>成果物を見る</button></div><section className="card blueprint situation"><Corners/><p className="kicker">今の状況</p><p>{summary}</p></section>{latest&&<section className="card consultation"><div><p className="kicker">確定した相談内容</p><Tag status={detail.approvals.some(x=>x.status==="approved")?"done":"neutral"}>{detail.approvals.some(x=>x.status==="approved")?"お客様承認済み":"確認中"}</Tag></div><p>{string(latest.summary)||string(latest.title)||string(latest.request_text)||"相談内容を受け付けています。"}</p></section>}{s==="in_progress"&&<section className="card progress-card"><h3>作業状況</h3>{detail.tasks.length?detail.tasks.map(t=><div className={`task ${t.status}`} key={t.id}><i><Icon name={t.status==="completed"?"check":"sparkle"} size={14}/></i><span>{string(t.title)||string(t.task_key)||"制作作業"}</span></div>):<Empty>作業項目を準備しています。</Empty>}</section>}{s==="needs_admin"&&<section className="card decision"><h3>確認が必要です</h3><p>{p.attention_reasons?.join("、")||"次の作業へ進む前に、内容を確認してください。"}</p><button className="btn btn-primary" onClick={()=>go("chat",p.id)}>司令塔AIに相談する</button></section>}{s==="done"&&<section className="card complete"><h3>完了しました</h3><p>承認と制作の記録が揃っています。本番公開はオーナー承認後にのみ実行されます。</p>{detail.artifacts.find(x=>x.preview_url)?.preview_url&&<a className="btn btn-secondary" target="_blank" rel="noreferrer" href={detail.artifacts.find(x=>x.preview_url)?.preview_url||""}>公開候補を見る <Icon name="external" size={14}/></a>}</section>}</Page>}
function Chat({projects,details,detail,go}:{projects:Project[];details:Record<string,Detail>;detail?:Detail;go:(s:Screen,id?:string)=>void}){if(!detail)return <Page title="AIチャット"><p className="muted">案件ごとの相談内容を確認できます。</p><div className="thread-list">{projects.map(x=>{const msgs=details[x.id]?.messages||[];return <button key={x.id} onClick={()=>go("chat",x.id)}><i><Icon name="sparkle"/></i><span><strong>{x.name}</strong><small>{x.customer_name}</small><p>{string(msgs.at(-1)?.content)||"まだメッセージはありません"}</p></span><Icon name="chevron" size={16}/></button>})}</div></Page>;const messages=detail.messages.filter(x=>string(x.author_type)!=="customer");return <Page title={detail.project.name} subtitle="司令塔AIとの相談" back={()=>go("project",detail.project.id)} narrow><div className="chat-messages">{messages.length?messages.map(m=><article key={m.id} className={string(m.author_type)==="admin"?"mine":"bot"}><p>{string(m.content)||"内容なし"}</p><time>{fmt(m.created_at,true)}</time></article>):<Empty>司令塔AIとの相談はまだありません。</Empty>}</div><div className="composer"><input className="input" value="" readOnly placeholder="この画面からの送信は現在準備中です" aria-label="AIへの相談"/><button className="btn btn-primary btn-icon" disabled aria-label="送信"><Icon name="send" size={16}/></button></div><p className="muted small">過去の実データのみ表示しています。未接続の送信を擬似的に成功させることはありません。</p></Page>}
function Page({title,subtitle,children,header,back,narrow=false}:{title:string;subtitle?:string;children:ReactNode;header?:ReactNode;back?:()=>void;narrow?:boolean}){return <div className={`page ${narrow?"narrow":""}`}>{back&&<button className="back" onClick={back}><Icon name="back" size={15}/>戻る</button>}<header className="page-header"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{header}</header>{children}</div>}
function Guide(){return <><p className="kicker">ステータスルール</p><div className="guide-list"><span><Tag>通常</Tag>特別な対応が不要な情報</span><span><Tag status="in_progress">進行中</Tag>AIまたは担当者が作業中</span><span><Tag status="needs_admin">確認が必要</Tag>判断・返信を待っている状態</span><span><Tag status="done">完了・正常</Tag>作業や支払いが完了</span><span><Tag status="error">エラー</Tag>すぐに確認が必要な異常</span></div><p className="muted small">色だけに頼らず、必ずアイコンと文言を併記します。</p><p className="kicker guide-heading">モーションルール</p><ul><li>新しいAI提案は控えめにフェードイン</li><li>状態の切り替わりは滑らかに表示</li><li>動きは状態変化を伝える目的に限定</li></ul><p className="kicker guide-heading">承認まわりの文言</p><p>「承認」だけで済ませず、制作を始める／お客様へ送る／公開する／料金を変更するなど、結果が分かる言葉を使います。</p></>}
