import { FormEvent, ReactNode, useCallback, useEffect, useMemo, useState } from "react";

type Summary = { customers:number; projects:number; needsAttention:number; runningWorkflows:number; failedTasks:number; pendingApprovals:number };
type Project = { id:string; name:string; status:string; customer_name?:string|null; needs_attention?:boolean; attention_reasons?:string[]; updated_at?:string };
type Overview = { summary:Summary; projects:Project[]; recentWorkflows:Record<string,unknown>[]; recentNotifications:Record<string,unknown>[] };
type Detail = { project:Project; customer?:{name?:string}|null; requests:Row[]; messages:Row[]; workflows:Row[]; tasks:Row[]; artifacts:Row[]; qualityChecks:Row[]; approvals:Row[]; payments:Row[]; repositories:Row[]; deployments:Row[]; auditLogs:Row[] };
type Row = Record<string, unknown> & { id:string; title?:string; status?:string; created_at?:string; preview_url?:string|null };
type Me = { profile?:{role?:string; displayName?:string}; user?:{email?:string}; onboardingRequired?:boolean };
type Tab = "overview"|"requests"|"workflow"|"artifacts"|"approvals"|"operations";

const core = import.meta.env.VITE_CORE_API_URL || "https://akinael-ai.com";
const tokenKey = "akinael-admin-token";
const fmt = (value:unknown) => typeof value === "string" && value ? new Intl.DateTimeFormat("ja-JP",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)) : "—";
const text = (value:unknown) => typeof value === "string" && value ? value : "—";

export default function Admin() {
  const recoveryParams=new URLSearchParams(window.location.hash.replace(/^#/,""));
  const recoveryToken=recoveryParams.get("access_token");
  const [token,setToken]=useState<string|null>(null),[me,setMe]=useState<Me|null>(null),[overview,setOverview]=useState<Overview|null>(null),[detail,setDetail]=useState<Detail|null>(null),[selected,setSelected]=useState(""),[tab,setTab]=useState<Tab>("overview"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState(""),[recoveryMode,setRecoveryMode]=useState(new URLSearchParams(window.location.search).get("mode")==="recovery"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const authHeaders=useCallback((value=token):Record<string,string>=>value?{authorization:`Bearer ${value}`}:{},[token]);
  const api=useCallback(async <T,>(path:string,value=token):Promise<T>=>{const response=await fetch(`${core}${path}`,{headers:authHeaders(value)});const body=await response.json().catch(()=>({}));if(!response.ok)throw Error(body?.error?.message||"管理データを取得できませんでした");return body as T},[authHeaders,token]);
  const load=useCallback(async(value=token,projectId?:string)=>{if(!value)return;const [who,board]=await Promise.all([api<Me>("/api/v2/auth/me",value),api<Overview>("/api/v2/admin/overview",value)]);if(who.profile?.role!=="admin")throw Error("管理者権限がありません。");setMe(who);setOverview(board);const id=projectId||selected||board.projects[0]?.id||"";setSelected(id);setDetail(id?await api<Detail>(`/api/v2/admin/projects/${id}`,value):null)},[api,selected,token]);
  useEffect(()=>{const saved=localStorage.getItem(tokenKey);if(!saved)return;setToken(saved);load(saved).catch(e=>{localStorage.removeItem(tokenKey);setToken(null);setError(e.message)})},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const login=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");try{const response=await fetch(`${core}/api/v2/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})});const body=await response.json();if(!response.ok)throw Error(body?.error?.message||"ログインに失敗しました");const who=await api<Me>("/api/v2/auth/me",body.token);if(who.profile?.role!=="admin")throw Error("管理者権限がありません。");localStorage.setItem(tokenKey,body.token);setToken(body.token);await load(body.token)}catch(e){setError(e instanceof Error?e.message:"ログインに失敗しました")}finally{setBusy(false)}};
  const requestRecovery=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");setNotice("");try{const response=await fetch(`${core}/api/v2/auth/password-recovery`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});const body=await response.json().catch(()=>({}));if(!response.ok)throw Error(body?.error?.message||"再設定メールを送信できませんでした");setNotice("パスワード再設定メールを送信しました。メール内のリンクを開いてください。")}catch(e){setError(e instanceof Error?e.message:"再設定メールを送信できませんでした")}finally{setBusy(false)}};
  const updatePassword=async(event:FormEvent)=>{event.preventDefault();setError("");setNotice("");if(password!==confirmPassword){setError("確認用パスワードが一致しません。");return}if(!recoveryToken){setError("回復リンクが無効です。再設定メールをもう一度送信してください。");return}setBusy(true);try{const response=await fetch(`${core}/api/v2/auth/password`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${recoveryToken}`},body:JSON.stringify({password})});const body=await response.json().catch(()=>({}));if(!response.ok)throw Error(body?.error?.message||"パスワードを更新できませんでした");window.history.replaceState({},"","/admin/");setPassword("");setConfirmPassword("");setRecoveryMode(false);setNotice("パスワードを更新しました。新しいパスワードでログインしてください。")}catch(e){setError(e instanceof Error?e.message:"パスワードを更新できませんでした")}finally{setBusy(false)}};
  const choose=async(id:string)=>{setSelected(id);setBusy(true);setError("");try{setDetail(await api<Detail>(`/api/v2/admin/projects/${id}`));setTab("overview")}catch(e){setError(e instanceof Error?e.message:"案件を取得できませんでした")}finally{setBusy(false)}};
  const logout=async()=>{if(token)await fetch(`${core}/api/v2/auth/logout`,{method:"POST",headers:authHeaders()}).catch(()=>{});localStorage.removeItem(tokenKey);setToken(null);setMe(null);setOverview(null);setDetail(null)};
  const totals=overview?.summary;
  const workflow=detail?.workflows?.[0];
  const grouped=useMemo(()=>({completed:detail?.tasks.filter(x=>x.status==="completed").length||0,total:detail?.tasks.length||0}),[detail]);
  if(!token||!me)return <main className="login-shell"><section className="login-card">
    <span className="brand-mark">A</span><p className="eyebrow">AKINAEL OPERATIONS</p>
    <h1>{recoveryMode?(recoveryToken?"新しいパスワード":"パスワード再設定"):"管理者ログイン"}</h1>
    <p className="muted">{recoveryMode?(recoveryToken?"12文字以上の新しいパスワードを設定します。":"登録済みメールアドレスへ安全な回復リンクを送信します。"):"Supabase Authで本人確認し、管理者ロールを検証します。"}</p>
    {error&&<p className="alert" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
    {recoveryMode?(recoveryToken?
      <form onSubmit={updatePassword}><label>新しいパスワード<input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} required /></label><label>新しいパスワード（確認）<input type="password" autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} minLength={12} required /></label><button disabled={busy}>{busy?"更新中…":"パスワードを更新"}</button></form>:
      <form onSubmit={requestRecovery}><label>メールアドレス<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required /></label><button disabled={busy}>{busy?"送信中…":"再設定メールを送信"}</button></form>):
      <form onSubmit={login}><label>メールアドレス<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required /></label><label>パスワード<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} required /></label><button disabled={busy}>{busy?"認証中…":"管理画面へ"}</button></form>}
    <div className="login-links">{recoveryMode?<button type="button" onClick={()=>{window.history.replaceState({},"","/admin/");setRecoveryMode(false);setError("");setNotice("")}}>ログインへ戻る</button>:<button type="button" onClick={()=>{window.history.replaceState({},"","/admin/?mode=recovery");setRecoveryMode(true);setError("");setNotice("")}}>パスワードを忘れた方</button>}<a href="/portal/">Customer Portalへ</a></div>
  </section></main>;
  return <div className="shell">
    <aside className="sidebar"><div><span className="brand-mark small">A</span><strong>AKINAEL</strong><small>Operations Console</small></div><nav aria-label="案件一覧"><p className="eyebrow">PROJECTS</p>{overview?.projects.map(p=><button key={p.id} className={selected===p.id?"active":""} onClick={()=>choose(p.id)}><span>{p.name}</span><small>{p.customer_name||"顧客未設定"} · {p.status}</small>{p.needs_attention&&<i aria-label="対応必要">!</i>}</button>)}</nav><button className="logout" onClick={logout}>ログアウト</button></aside>
    <main className="workspace"><header className="top"><div><p className="eyebrow">ADMIN / TENANT OPERATIONS</p><h1>{detail?.project.name||"運用ダッシュボード"}</h1><p className="muted">{detail?.customer?.name||"案件を選択してください"} · 最終更新 {fmt(detail?.project.updated_at)}</p></div><div className="operator"><span>{me.profile?.displayName||"管理者"}</span><small>{me.user?.email}</small><button onClick={()=>load(token,selected)} disabled={busy}>更新</button></div></header>
      {error&&<p className="alert" role="alert">{error}</p>}
      <section className="metrics" aria-label="運用サマリー"><Metric label="顧客" value={totals?.customers}/><Metric label="案件" value={totals?.projects}/><Metric label="対応必要" value={totals?.needsAttention} tone="warn"/><Metric label="進行中Workflow" value={totals?.runningWorkflows}/><Metric label="失敗Task" value={totals?.failedTasks} tone="danger"/><Metric label="承認待ち" value={totals?.pendingApprovals}/></section>
      {detail&&<><nav className="tabs" aria-label="案件詳細">{([["overview","概要"],["requests","依頼・会話"],["workflow","Workflow"],["artifacts","成果物・品質"],["approvals","承認"],["operations","運用記録"]] as [Tab,string][]).map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>
      {tab==="overview"&&<section className="panel-grid"><Panel title="現在の状態"><Status label="Project" value={detail.project.status}/><Status label="Workflow" value={workflow?.status}/><Status label="Phase" value={workflow?.current_phase}/><Status label="Tasks" value={`${grouped.completed} / ${grouped.total} 完了`}/></Panel><Panel title="Human Gate"><p>本番公開・DNS変更・新規課金・返金・データ削除は、承認記録を確認後にのみ実行します。</p><div className="gate">自動実行なし</div></Panel><Panel title="対応理由"><List rows={(detail.project.attention_reasons||[]).map((v,i)=>({id:String(i),title:v}))} empty="対応必要事項はありません。"/></Panel><Panel title="リポジトリ"><List rows={detail.repositories.map(x=>({...x,title:text(x.repository_full_name),status:text(x.default_branch)}))} empty="リポジトリ未登録"/></Panel></section>}
      {tab==="requests"&&<section className="panel-grid"><Panel title={`依頼 ${detail.requests.length}件`}><List rows={detail.requests} empty="依頼はありません。"/></Panel><Panel title={`メッセージ ${detail.messages.length}件`}><List rows={detail.messages.map(x=>({...x,title:text(x.author_type),status:text(x.content)}))} empty="メッセージはありません。"/></Panel></section>}
      {tab==="workflow"&&<section className="panel-grid"><Panel title={`Workflow ${detail.workflows.length}件`}><List rows={detail.workflows.map(x=>({...x,title:text(x.pipeline),status:`${text(x.status)} / ${text(x.current_phase)}`}))} empty="Workflowはありません。"/></Panel><Panel title={`Tasks ${detail.tasks.length}件`}><List rows={detail.tasks} empty="Taskはありません。"/></Panel></section>}
      {tab==="artifacts"&&<section className="panel-grid"><Panel title={`成果物 ${detail.artifacts.length}件`}><List rows={detail.artifacts} empty="成果物はありません。" links/></Panel><Panel title={`品質検査 ${detail.qualityChecks.length}件`}><List rows={detail.qualityChecks.map(x=>({...x,title:text(x.reviewer),status:`${text(x.status)} · ${text(x.severity)}`}))} empty="品質検査記録はありません。"/></Panel></section>}
      {tab==="approvals"&&<section className="panel-grid"><Panel title={`承認 ${detail.approvals.length}件`}><List rows={detail.approvals.map(x=>({...x,title:text(x.type)}))} empty="承認記録はありません。"/></Panel><Panel title={`決済 ${detail.payments.length}件`}><List rows={detail.payments.map(x=>({...x,title:`${text(x.amount)} ${text(x.currency)}`,status:text(x.status)}))} empty="決済記録はありません。"/><div className="gate">新規課金はHuman Gate</div></Panel></section>}
      {tab==="operations"&&<section className="panel-grid"><Panel title={`Deployments ${detail.deployments.length}件`}><List rows={detail.deployments.map(x=>({...x,title:text(x.environment),status:text(x.status)}))} empty="デプロイ記録はありません。"/></Panel><Panel title={`監査ログ ${detail.auditLogs.length}件`}><List rows={detail.auditLogs.map(x=>({...x,title:text(x.action),status:text(x.resource_type)}))} empty="監査ログはありません。"/></Panel></section>}</>}
    </main>
  </div>
}

function Metric({label,value,tone=""}:{label:string;value?:number;tone?:string}){return <article className={tone}><span>{label}</span><strong>{value??"—"}</strong></article>}
function Panel({title,children}:{title:string;children:ReactNode}){return <article className="panel"><h2>{title}</h2>{children}</article>}
function Status({label,value}:{label:string;value:unknown}){return <div className="status-row"><span>{label}</span><strong>{text(value)}</strong></div>}
function List({rows,empty,links=false}:{rows:Row[];empty:string;links?:boolean}){if(!rows.length)return <p className="empty">{empty}</p>;return <ul className="record-list">{rows.slice(0,100).map(row=><li key={row.id}><div><strong>{row.title||text(row.kind)||text(row.task_key)||row.id}</strong><small>{row.status&&String(row.status)}{row.created_at&&` · ${fmt(row.created_at)}`}</small></div>{links&&row.preview_url&&<a href={row.preview_url} target="_blank" rel="noreferrer">プレビュー ↗</a>}</li>)}</ul>}
