"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
type Project={id:string;name:string;status?:string;plan?:string}; type Production={workflows?:Array<{status?:string}>;tasks?:Array<{task_key:string;status:string}>;artifacts?:Array<{id:string;kind:string;title?:string;created_at?:string;preview_url?:string}>}; type RequestItem={id:string;title?:string;body?:string;status?:string}; type Message={id:string;content:string;author_type?:string;created_at?:string}; type Me={email?:string;onboardingRequired?:boolean;customer?:{displayName?:string;businessName?:string}};
const core=process.env.NEXT_PUBLIC_CORE_API_URL||"https://akinael-ai.com"; const tokenKey="customer-token";
export default function PortalPage(){
 const [mounted,setMounted]=useState(false),[token,setToken]=useState<string|null>(null),[projects,setProjects]=useState<Project[]>([]),[production,setProduction]=useState<Production|null>(null),[requests,setRequests]=useState<RequestItem[]>([]),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(""),[error,setError]=useState(""),[me,setMe]=useState<Me|null>(null),[authMode,setAuthMode]=useState<"login"|"register">("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[displayName,setDisplayName]=useState(""),[businessName,setBusinessName]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const headers=useCallback((t=token)=>t?{authorization:`Bearer ${t}`}:{},[token]);
 const refresh=useCallback(async(t=token)=>{if(!t)return;const h={authorization:`Bearer ${t}`},mr=await fetch(`${core}/api/v2/auth/me`,{headers:h});if(!mr.ok)throw new Error("セッションの有効期限が切れています。公開サイトから再度ログインしてください。");const account=await mr.json();setMe(account);const ps=await fetch(`${core}/api/v2/projects`,{headers:h});if(!ps.ok)throw new Error("案件を取得できませんでした");const list=await ps.json();setProjects(list);const p=list[0];if(!p)return;const [pr,rr,mm]=await Promise.all([fetch(`${core}/api/v2/projects/${p.id}/production`,{headers:h}),fetch(`${core}/api/v2/projects/${p.id}/requests`,{headers:h}),fetch(`${core}/api/v2/projects/${p.id}/messages`,{headers:h})]);setProduction(pr.ok?await pr.json():null);setRequests(rr.ok?await rr.json():[]);setMessages(mm.ok?await mm.json():[]);},[token]);
 useEffect(()=>{const timer=window.setTimeout(()=>setMounted(true),250);return()=>window.clearTimeout(timer)},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>{const t=window.localStorage.getItem(tokenKey);setToken(t);if(t)refresh(t).catch(e=>setError(e.message));},0);return()=>window.clearTimeout(timer)},[refresh]);
 const authenticate=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const ep=authMode==="login"?"login":"register",r=await fetch(`${core}/api/v2/auth/${ep}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})}),data=await r.json();if(!r.ok)throw new Error(data?.error?.message||"認証に失敗しました");if(data.confirmationRequired){setNotice("確認メールを開き、確認後にログインしてください。");return}window.localStorage.setItem(tokenKey,data.token);setToken(data.token);await refresh(data.token);}catch(e){setError(e instanceof Error?e.message:"認証に失敗しました")}finally{setBusy(false)}};
 const completeOnboarding=async(e:FormEvent)=>{e.preventDefault();if(!token)return;setBusy(true);try{const r=await fetch(`${core}/api/v2/onboarding`,{method:"POST",headers:{...headers(),"content-type":"application/json"},body:JSON.stringify({displayName,businessName})});if(!r.ok)throw new Error("プロフィールを保存できませんでした");await refresh()}catch(e){setError(e instanceof Error?e.message:"保存に失敗しました")}finally{setBusy(false)}};
