import { test, expect, type Page } from "@playwright/test";

const overview={summary:{customers:2,projects:2,needsAttention:1,runningWorkflows:1,failedTasks:0,pendingApprovals:1},projects:[{id:"project-1",customer_id:"customer-1",name:"月灯り珈琲 Webサイト制作",status:"production",customer_name:"月灯り珈琲",needs_attention:true,attention_reasons:["制作内容の確認"],updated_at:"2026-09-16T06:00:00Z"},{id:"project-2",customer_id:"customer-2",name:"海辺商店 ブランドサイト",status:"completed",customer_name:"海辺商店",updated_at:"2026-09-15T06:00:00Z"}],recentWorkflows:[],recentNotifications:[]};
const detail=(project=overview.projects[0])=>({project,customer:{id:project.customer_id,name:project.customer_name,created_at:"2026-08-01T00:00:00Z"},requests:[{id:"request-1",title:"予約導線を分かりやすくしたい",created_at:"2026-09-14T00:00:00Z"}],messages:[{id:"message-1",author_type:"customer",content:"写真を大きく使いたいです。",created_at:"2026-09-14T01:00:00Z"},{id:"message-2",author_type:"assistant",content:"ご要望を整理しました。",created_at:"2026-09-14T01:01:00Z"}],workflows:[{id:"workflow-1",status:project.id==="project-1"?"running":"completed"}],tasks:[{id:"task-1",title:"構成を作成",status:"completed"},{id:"task-2",title:"デザインを制作",status:project.id==="project-1"?"running":"completed"}],artifacts:[{id:"artifact-1",title:"Webサイト",preview_url:"https://example.com/preview",created_at:"2026-09-15T00:00:00Z"}],qualityChecks:[],approvals:[{id:"approval-1",status:project.id==="project-1"?"pending":"approved"}],payments:[],repositories:[],deployments:[],notifications:[],deploymentGate:{releasePassed:project.id!=="project-1",customerApproved:project.id!=="project-1",deployReady:project.id!=="project-1",humanGateRequired:true,productionPublished:project.id!=="project-1"},auditLogs:[]});

async function mockApp(page:Page){await page.addInitScript(()=>localStorage.setItem("akinael-admin-token","test-token"));await page.route("**/api/v2/auth/me",r=>r.fulfill({contentType:"application/json",body:JSON.stringify({profile:{role:"admin",displayName:"管理者"},user:{email:"owner@example.com"}})}));await page.route("**/api/v2/admin/overview",r=>r.fulfill({contentType:"application/json",body:JSON.stringify(overview)}));await page.route("**/api/v2/admin/projects/*",r=>{const id=r.request().url().split("/").pop();const project=overview.projects.find(p=>p.id===id)||overview.projects[0];return r.fulfill({contentType:"application/json",body:JSON.stringify(detail(project))})})}

for(const viewport of [{width:390,height:844},{width:375,height:812}])test.describe(`mobile ${viewport.width}x${viewport.height}`,()=>{test.use({viewport});test("responsive navigation, real-data screens, reload, and console",async({page})=>{const errors:string[]=[];page.on("console",m=>{if(m.type()==="error")errors.push(m.text())});page.on("pageerror",e=>errors.push(String(e)));await mockApp(page);await page.goto("/admin/");await expect(page.getByRole("heading",{name:"ホーム"})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await expect(page.locator(".sidebar")).toBeHidden();await expect(page.locator(".bottom-nav")).toBeVisible();await page.getByRole("button",{name:"案件"}).last().click();await expect(page.getByRole("heading",{name:"案件"})).toBeVisible();await page.getByText("月灯り珈琲 Webサイト制作").last().click();await expect(page.getByRole("heading",{name:"月灯り珈琲 Webサイト制作"})).toBeVisible();await page.reload();await expect(page.getByRole("heading",{name:"ホーム"})).toBeVisible();expect(errors).toEqual([])})});

test("desktop matches the source IA and all primary screens are reachable",async({page})=>{await page.setViewportSize({width:1440,height:960});await mockApp(page);await page.goto("/admin/");await expect(page.locator(".app-shell")).toHaveCSS("display","grid");await expect(page.locator(".sidebar")).toBeVisible();for(const label of ["顧客","案件","AIチャット","制作物","契約・料金","設定"]){await page.locator(".sidebar nav").getByRole("button",{name:label,exact:true}).click();await expect(page.getByRole("heading",{name:label})).toBeVisible()}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)});
